//Include section
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
//Define section
#define MAX_GUESS 10
#define MAX_RANDOM 100

// ------ Function declarations ----------

// Creates a new game of the random number guessing game.
void play(int *guess,int *guesses,int *randomNumber, char* userInput);

// ------ Function declarations ----------

//Main program section

/**
* This program is a game where the user has to guess a number
* that is generated by the computer. The user has a limited
* number of guesses and has to guess the number with as few guesses
* as possible. 
* 
* Purpose: The purpose of this program is to entertain the user
* and allow the user to practice their skills of guessing random numbers.
* DIT632
* 
* Author: Kaisa Arumeel, Omid Khodaparast, Alexander Säfström
* 
**/

int main(int argc,char* argv[]){
    // Variable declarations
    time_t currentTime; // The current system time
    int randomNumber; // A random number between 1 and 100.
    int guesses; // Number of guesses
    char userInput[MAX_RANDOM]; // The user's input limited by the upper limit (100)
    int guess;
    //Program logic 

    // Get the current system time
    currentTime=time(NULL);

    // Seed the random number generator with the current time.
    srand(currentTime);

    // Call the function that contains the game
    play(&guess,&guesses,&randomNumber,userInput);

    // Exit the program gracefully
    return 0;
}

void play(int *guess,int *guesses,int *randomNumber, char* userInput){

    // Update the random number
    *randomNumber=rand()%MAX_RANDOM;    

    // Initialize the number of guesses to 0
    *guesses=0;

    // Initialize the current guess to be -1
    // signifying that the user has not guessed yet.
    *guess=-1;

    do {
        // If the user has guessed
        if(*guess!=-1){
            // If the guess is bigger than the random number
            if(*guess>*randomNumber){
                // Print hint
                printf("Your guess is too high.\n");
            } else if(*guess<*randomNumber){
                // If the guess is smaller than the random number
                // Print hint
                printf("Your guess is too low.\n");
            }
        }
        // Prompt the user to guess the number.
        printf("Guess the number.\n");

        // Read the next MAX_RANDOM length from the standard input
        fgets(userInput,MAX_RANDOM,stdin);

        // Convert the users input into an integer.
        *guess=atoi(userInput);

        // Increment the number of guesses a user has made.
        *guesses+=1;
     
        // We iterate in this while loop while the guess is not correct
        // and while the number of guesses is less than the maximum
    } while(*guess!=*randomNumber && *guesses<MAX_GUESS);

    // If the guess is correct
    if(*guess==*randomNumber){
        // Print to the screen
        printf("You have guessed %d times and your guess is correct.\n",*guesses);
    } else {
        // Print to the screen
        printf("You have run out of guesses!\n");
    }
    // Prompt the user to play again
    printf("Would you like to play again? (y or n)\n");
    // Read at most the next 3 chars
    // This will include the y or n and the \n char.
    fgets(userInput,3,stdin);
    // If the user's input is y
    if(*(userInput)=='y'){
        // Let the function call itself and play again.
        play(guess,guesses,randomNumber,userInput);
    }
}